### ISSUE TITLE
about "The Efficient Diffusion Model for Image Restoration by Residual Shifting"

### ISSUE THREAD

**Issue by KasuganoLove** [ChunmingHe/awesome-diffusion-models-in-low-level-vision#3]
`The Efficient Diffusion Model for Image Restoration by Residual Shifting` is actually an extended version of ResShift, which is worth mentioning.

**Comment by EricShenYuQi** [comment]
Thank you for your advice! We have already mentioned the work in the list.

**Comment by KasuganoLove** [comment]
> We have already mentioned the work in the list.

Thank you for the feedback. I think it would be beneficial to clarify the connection between article `The Efficient Diffusion Model for Image Restoration by Residual Shifting` and `ResShift` in the readme.

**Comment by ChunmingHe** [comment]
Cool, we will do this!
