### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by Yaofang-Liu** [ChunmingHe/awesome-diffusion-models-in-low-level-vision#4]
Hi, please see if you could add this paper about a new kind of diffusion model for super-resolution and low light enhancement
Title: Super-resolving Real-world Image Illumination Enhancement: A New Dataset and A Conditional Diffusion Model
arXiv: https://arxiv.org/abs/2410.12961
GitHub: https://github.com/Yaofang-Liu/Super-Resolving

Many thanks for your awesome list!

**Comment by ChunmingHe** [comment]
Thanks for reminding us, I have briefly read this interesting paper and I
will add this paper to this repository. Besides, I’d like to recommend you
to our new survey: Diffusion Models in Low-Level Vision: A Survey
<https://arxiv.org/abs/2406.11138>

I hope this paper proves helpful in your future research!

LIU Yaofang ***@***.***> 于2024年10月21日周一 11:26写道：

**Comment by Yaofang-Liu** [comment]
Thank you very much! Will write the related work for future papers based on the survey you recommended. Really appreciate your great work 👍
